import './css/style.css'

import { Inter } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'
import { brush } from '@/lib/fonts'
import { GoogleAnalytics } from '@next/third-parties/google'
import ogImage from "@/../public/images/opengraph-image.png"
import { auth } from '@/auth'
import SessionProvider from '@/components/SessionProvider'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	display: 'swap'
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	metadataBase: new URL("https://www.booklinkr.com/"),
	openGraph: {
		images: [
			{
				url: ogImage.src,
				width: ogImage.width,
				height: ogImage.height
			},
		],
	},
	twitter: {
		images: [
			{
				url: ogImage.src,
				width: ogImage.width,
				height: ogImage.height
			},
		]
	},
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const session = await auth()
	return (
		<html lang="en">
			<body className={`${brush.className} antialiased bg-lightbrown text-darkgreen tracking-tight`}>
				<SessionProvider session={session}>
					<div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
						<Header />
						{JSON.stringify(session)}
						{children}
						{/* <Banner /> */}
					</div>
				</SessionProvider>
			</body>
			<GoogleAnalytics gaId='G-Y3ERXF2YTE' />
		</html>
	)
}
